### ISSUE TITLE
Odd use of time.Duration in the client API

### ISSUE THREAD

**Issue by justinruggles** [appscode/g2#28]
It seems a very strange API to use time.Duration for Client.ResponseTimeout but specify that it's in milliseconds. One of the points of time.Duration is to abstract the time unit. It's very unintuitive to someone who has been using Go for years to use it in the way you've specified it.

I understand that it would be an API break to change it, but I wanted to note it because it led to a bug on my end that was very difficult to debug.

**Comment by TamalSaha** [comment]
@justinruggles , thanks for reporting the issue. We have fixed this is 0.5.0 release.
